//TODO create html skalton (5min)
//TODO get the user id (2min)
//TODO get user name and photo from firebase firestore(5min)
//TODO add func for story(2min)
//TODO  get story id (2min)
//TODO  get story description(2min)
//TODO add func for user profile(2min)
//TODO  get user bio (2min)