//TODO get the object that is will be purchased(5min)
//TODO add a cloud funcation for giveing every user a stripe id(10min)
//TODO add a cloud funcation for savaing the card detaels (15min)
//TODO add a cloud funcation for purchasing an item (15min)
//TODO add a cloud funcation for subscribing  (20min)
//TODO import stripe(5min)
//TODO add a loading eleminent(5min)
//TODO add stripe card element(15min) 
//TODO display the stripe card errors(10min) 
//TODO call the add card funcation(10min)
//TODO get the response(5min)
//TODO display the card erros(15min)
//TODO start the 3d auth if the response 3d(25min) 
//TODO add a cloud funcation for getting the purchsing object again(10min)
//TODO add a cloud funcation for if the purchsing object status is complieted add the item to the user object(20min)
//TODO display any purchasing errors(5min)
