//DONE make a flow chart
//TODO create video tag(3min)
//TODO add a funcation to handle camera requaset(5min)
//TODO handel camera requaste erros(5min)
//TODO get camera feed(5min)
//TODO add start fucation(2min)
//TODO start display camera feed(5min)
//TODO start recording(3min)
//TODO add get move func(2min)
//TODO trigger get move when chessboard changes(10min)
//TODO get move and time (5mim)
//TODO add move and time to timestamps obj(5min)
//TODO add pause funcation(5min)
//TODO add rusme funcation(5min)
//TODO add stop funcation(5min)
//TODO create the mp4 file (3min)
